name: 'Benfica'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform job'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./deploy
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
          terraform_version: 1.6.6
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
    - name: Terraform Apply
      run: terraform apply -auto-approve