name: Create prerelease tag

on:
  push:
    branches:
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits
      - name: Create tag
        run: |
            major=${{ steps.release.outputs.new_release_major_version }}
            minor=${{ steps.release.outputs.new_release_minor_version }}
            patch=${{ steps.release.outputs.new_release_patch_version }}

            version_release_candidates_number=$(git tag --list $major.$minor.$patch-rc.* | wc -l)
            release_candidate_number=$(($version_release_candidates_number + 1))

            git tag ${{ steps.release.outputs.new_release_version }}-rc.$release_candidate_number
