name: Create prerelease tag

on:
  push:
    branches:
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits
      - name: Calculate release candidate number
        id: calc-rc
        run: |
            major=${{ steps.release.outputs.new_release_major_version }}
            minor=${{ steps.release.outputs.new_release_minor_version }}
            patch=${{ steps.release.outputs.new_release_patch_version }}

            version_release_candidates_number=$(git tag --list $major.$minor.$patch-rc.* | wc -l)
            rc_number=$(($version_release_candidates_number + 1))
            echo "rc_new_version="$major.$minor.$patch-rc.$rc_number" >> "$GITHUB_OUTPUT"
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.calc-rc.outputs.rc_new_version }}',
              sha: context.sha
            })