name: Destroy app

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: Environment
        options: 
        - staging
        - rc

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./deploy
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: terraform init -backend-config="./backend/${{ github.event.inputs.environment }}.config"
    - name: Terraform destroy
      run: terraform destroy